<a href="https://colab.research.google.com/github/tata-lakshman/Pandas/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

                 #pandas
Why pandas?
Import datasets=>csv,excel,tsv,sql,etc.
Data Cleaning=>missing values(blank values)&invalid values.
size mutable=>we can easily add delete colums or rows.
Reshape and pivoting of datasets.
Efficien manipulation and extraction.
Statistical analysis.
      #2 Primary dataStructurs 1)Series(1D) 2)Data frame(2D)
Data Structures are collection of datatypes that provide the best way of organizing items(values) in terms of memory usage.
1)Series=>A one-dimensional labeled homogeneous array,size immutable(we can't delete particular row from there we can only remove it.)
2)Data Frames=>A two-dimensional labeled,size-mutable tabular structure with potentially heterogenously typed columns.

In [ ]:
import pandas as pd
s=pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
s=pd.Series([10,20,30,40,'abc'])
print(s)

0     10
1     20
2     30
3     40
4    abc
dtype: object

#we can assign different index values as well

In [ ]:
s2=pd.Series([10,20,30,40],index=['a','b','c','d'])
print(s2)

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
print(s.dtype)

object

In [ ]:
print(s.values)

[10 20 30 40 'abc']

In [ ]:
print(s.index)

RangeIndex(start=0, stop=5, step=1)

In [ ]:
print(s2.index)

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
print(s.name)

None

In [ ]:
s.name="mixed"
print(s)

0     10
1     20
2     30
3     40
4    abc
Name: mixed, dtype: object

In [ ]:
print(s.name)

mixed

In [ ]:
s=pd.Series([10,20,30,40,50])
s.name="Numbers"
print(s)

0    10
1    20
2    30
3    40
4    50
Name: Numbers, dtype: int64

In [ ]:
#indexing
s[0]

np.int64(10)

In [ ]:
print(s[0:2])

0    10
1    20
Name: Numbers, dtype: int64

             #iloc=>Location based indexing
.iloc is used for integer-location based indexing in pandas DataFrames and Series. It allows you to select data based on its numerical position (from 0 to n-1) in the index, rather than its label. This is in contrast to .loc, which is used for label-based indexing.

For example, s.iloc[3] retrieves the element at the 4th position (index 3) in the Series s, regardless of what the actual index labels are. If you had a DataFrame, you could use .iloc to select rows and columns by their integer position, like df.iloc[0, 1] to get the element in the first row and second column.

In [ ]:
print(s.iloc[3])

40

In [ ]:
print(s.iloc[[1, 3, 4]])

1    20
3    40
4    50
Name: Numbers, dtype: int64

In [ ]:
s

0    10
1    20
2    30
3    40
4    50
Name: Numbers, dtype: int64

In [ ]:
s.name="calories"
index=["apple","banana","cherry","orange","kiwi"]
s.index=index
print(s)

apple     10
banana    20
cherry    30
orange    40
kiwi      50
Name: calories, dtype: int64

In [ ]:
print(s.iloc["banana"])

TypeError: Cannot index by location index with a non-integer key

#TypeError: Cannot index by location index with a non-integer key means you are trying to use .iloc with a non-integer index label, 'banana'.

Remember, .iloc is used for integer-location based indexing (using the numerical position, like 0, 1, 2, etc.), while .loc is used for label-based indexing (using the actual index labels, like 'apple', 'banana', etc.).

To access the value for 'banana', you should use .loc:

#It performs operations on original index only
s.iloc[2]=>But how can we know that 3rd index has banana.Here comes(loc)

In [ ]:
s

apple     10
banana    20
cherry    30
orange    40
kiwi      50
Name: calories, dtype: int64

            #loc=>label-based indexing.
Think of your Series s with index labels 'apple', 'banana', 'cherry', etc. When you use s.loc['banana'], pandas looks for the index label 'banana' and returns the corresponding value.

This is different from .iloc, which uses the integer position (0, 1, 2, ...) to select data. So, s.iloc[1] would give you the element at the second position (index 1), which happens to be 'banana' in your current Series, but it's selected by position, not label.

.loc is particularly useful when your index has meaningful labels, as it makes your code more readable and less prone to errors if the order of your data changes.

In [ ]:
#loc=>location based indexing
print(s.loc['banana'])

20

#In label-based indexing(loc) your start as well as stop value both are included in the output.

In [ ]:
s['banana':'orange']

banana    20
cherry    30
orange    40
Name: calories, dtype: int64

#The main difference between .iloc and .loc in pandas lies in how they select data:

.iloc (integer-location based indexing): This method uses the integer position of the rows and columns to select data. It's like accessing elements in a Python list or array using their numerical index (starting from 0). You use integers or slices of integers with .iloc.
.loc (label-based indexing): This method uses the actual labels of the index and columns to select data. You use the labels (strings, numbers, or a mix) that are present in the index and column names with .loc.

In short:

Use .iloc when you want to select data based on its position.

Use .loc when you want to select data based on its label.

In [ ]:
#Dictionary
fruit_proten={
    "Avacado":2.0,
    "Guava":2.6,
    "Blackberry":2.0,
    "Orange":0.9,
    "Banana":1.1,
    "Apple":0.3,
    "Kiwi":1.1,
    "Promegranate":1.7,
    "Mango":0.8,
    "Cherry":1.0
}
s3=pd.Series(fruit_proten,name="Protein")
s3

Avacado         2.0
Guava           2.6
Blackberry      2.0
Orange          0.9
Banana          1.1
Apple           0.3
Kiwi            1.1
Promegranate    1.7
Mango           0.8
Cherry          1.0
Name: Protein, dtype: float64

In [ ]:
#conditional Selection (true,false)
s3>1

Avacado          True
Guava            True
Blackberry       True
Orange          False
Banana           True
Apple           False
Kiwi             True
Promegranate     True
Mango           False
Cherry          False
Name: Protein, dtype: bool

s3 > 1: This part creates a boolean Series of the same size as s3. For each element in s3, it checks if the value is greater than 1. If it is, the corresponding value in the boolean Series is True; otherwise, it's False.

s3[...]: When you use this boolean Series inside the square brackets [] after s3, pandas returns only the elements from s3 where the corresponding value in the boolean Series is True.

So, s3[s3 > 1] effectively filters the s3 Series and shows you only the fruits that have a protein value greater than 1.

In [ ]:
s3[s3>1]

Avacado         2.0
Guava           2.6
Blackberry      2.0
Banana          1.1
Kiwi            1.1
Promegranate    1.7
Name: Protein, dtype: float64

In [ ]:
#Logical operators:and,or,not
[(s3>0.5) & (s3<1)]

[Avacado         False
 Guava           False
 Blackberry      False
 Orange           True
 Banana          False
 Apple           False
 Kiwi            False
 Promegranate    False
 Mango            True
 Cherry          False
 Name: Protein, dtype: bool]

In [ ]:
s3[(s3>0.5) & (s3<1)]

Orange    0.9
Mango     0.8
Name: Protein, dtype: float64

In [ ]:
s3[(s3>1) | (s3<=2)]

Avacado         2.0
Guava           2.6
Blackberry      2.0
Orange          0.9
Banana          1.1
Apple           0.3
Kiwi            1.1
Promegranate    1.7
Mango           0.8
Cherry          1.0
Name: Protein, dtype: float64

In [ ]:
#not operation
s3[~(s3<1)]

Avacado         2.0
Guava           2.6
Blackberry      2.0
Banana          1.1
Kiwi            1.1
Promegranate    1.7
Cherry          1.0
Name: Protein, dtype: float64

In [ ]:
#modyfying the Series
s3["kiwi"]=2.8
s3

Avacado         2.0
Guava           2.6
Blackberry      2.0
Orange          0.9
Banana          1.1
Apple           0.3
Kiwi            1.1
Promegranate    1.7
Mango           0.8
Cherry          1.0
kiwi            2.8
Name: Protein, dtype: object

In [ ]:
print(s3.loc["Mango"])

0.8

In [ ]:
import numpy as np
ser=pd.Series(['a',np.nan,1,np.nan,23])

ser.notnull().sum()

np.int64(3)

In [ ]:
print(ser.dtype)

object

In [ ]:
#Data Frame:
data={
    "Name":["Alice","Bob","Charlie","David","Eve","Alice"],
    "Age":[25,30,22,np.nan,28,35],
    "Department":["HR","IT","Finance","HR","IT","HR"],
    "Salary":[50000,60000,55000,np.nan,62000,70000]
}
print(data)

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'], 'Age': [25, 30, 22, nan, 28, 35], 'Department': ['HR', 'IT', 'Finance', 'HR', 'IT', 'HR'], 'Salary': [50000, 60000, 55000, nan, 62000, 70000]}

In [ ]:
df=pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  22.0    Finance  55000.0
3    David   NaN         HR      NaN
4      Eve  28.0         IT  62000.0
5    Alice  35.0         HR  70000.0

In [ ]:
df.head()#By default it will give 5 values.

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  22.0    Finance  55000.0
3    David   NaN         HR      NaN
4      Eve  28.0         IT  62000.0

In [ ]:
df.head(2)

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0

In [ ]:
df.tail(3)#By default it will give bottem 5 rows.

    Name   Age Department   Salary
3  David   NaN         HR      NaN
4    Eve  28.0         IT  62000.0
5  Alice  35.0         HR  70000.0

In [ ]:
#loc and iloc
df.iloc[3]

Name          David
Age             NaN
Department       HR
Salary          NaN
Name: 3, dtype: object

In [ ]:
df.iloc[1:4]

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  22.0    Finance  55000.0
3    David   NaN         HR      NaN

In [ ]:
df.iloc[1:4,0:2]

      Name   Age
1      Bob  30.0
2  Charlie  22.0
3    David   NaN

In [ ]:
df.loc[1:3,["Age","Department"]]

    Age Department
1  30.0         IT
2  22.0    Finance
3   NaN         HR

In [ ]:
df["Age"]

0    25.0
1    30.0
2    22.0
3     NaN
4    28.0
5    35.0
Name: Age, dtype: float64

In [ ]:
df.drop("Age",axis=1)

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  55000.0
3    David         HR      NaN
4      Eve         IT  62000.0
5    Alice         HR  70000.0

In [ ]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  22.0    Finance  55000.0
3    David   NaN         HR      NaN
4      Eve  28.0         IT  62000.0
5    Alice  35.0         HR  70000.0

In [ ]:
df

  Department   Salary
0         HR  50000.0
1         IT  60000.0
2    Finance  55000.0
3         HR      NaN
4         IT  62000.0
5         HR  70000.0

In [ ]:
df.shape

(6, 2)

In [ ]:
import pandas as pd
df1=pd.DataFrame(data)
df1

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  22.0    Finance  55000.0
3    David   NaN         HR      NaN
4      Eve  28.0         IT  62000.0
5    Alice  35.0         HR  70000.0

In [ ]:
df1.shape

(6, 4)

In [ ]:
df1.info

<bound method DataFrame.info of       Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  22.0    Finance  55000.0
3    David   NaN         HR      NaN
4      Eve  28.0         IT  62000.0
5    Alice  35.0         HR  70000.0>

In [ ]:
df.describe()

             Salary
count      5.000000
mean   59400.000000
std     7536.577473
min    50000.000000
25%    55000.000000
50%    60000.000000
75%    62000.000000
max    70000.000000

In [ ]:
#Broad Casting
df["Salary"]=df["Salary"]+5000
df

  Department   Salary
0         HR  55000.0
1         IT  65000.0
2    Finance  60000.0
3         HR      NaN
4         IT  67000.0
5         HR  75000.0

In [ ]:
#Renaming Column
df.rename(columns={"Department":"Dept"},inplace=True)
df

      Dept   Salary
0       HR  55000.0
1       IT  65000.0
2  Finance  60000.0
3       HR      NaN
4       IT  67000.0
5       HR  75000.0

In [ ]:
df1.rename(columns={"Department":"Dept"},inplace=True)
df1

      Name   Age     Dept   Salary
0    Alice  25.0       HR  50000.0
1      Bob  30.0       IT  60000.0
2  Charlie  22.0  Finance  55000.0
3    David   NaN       HR      NaN
4      Eve  28.0       IT  62000.0
5    Alice  35.0       HR  70000.0

In [ ]:
df["Salary"].unique()

array([55000., 65000., 60000.,    nan, 67000., 75000.])

In [ ]:
df["Dept"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [ ]:
df1["Name"].unique()

array(['Alice', 'Bob', 'Charlie', 'David', 'Eve'], dtype=object)

In [ ]:
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [ ]:
df["Promotion Salary"]=df["Salary"]*10
df

      Dept   Salary  Promotion Salary
0       HR  55000.0          550000.0
1       IT  65000.0          650000.0
2  Finance  60000.0          600000.0
3       HR      NaN               NaN
4       IT  67000.0          670000.0
5       HR  75000.0          750000.0

In [ ]:
#Data Cleaning
df.isnull().sum()

Dept                0
Salary              1
Promotion Salary    1
dtype: int64

In [ ]:
df1.isnull().sum()

Name      0
Age       1
Dept      0
Salary    1
dtype: int64

In [ ]:
df.dropna()#With out passing any parameter so where the nullvalues are there the rows are removed and it doesn't effect the original dataset(we did'n use inplace=True)

      Dept   Salary  Promotion Salary
0       HR  55000.0          550000.0
1       IT  65000.0          650000.0
2  Finance  60000.0          600000.0
4       IT  67000.0          670000.0
5       HR  75000.0          750000.0

In [ ]:
df

      Dept   Salary  Promotion Salary
0       HR  55000.0          550000.0
1       IT  65000.0          650000.0
2  Finance  60000.0          600000.0
3       HR      NaN               NaN
4       IT  67000.0          670000.0
5       HR  75000.0          750000.0

In [ ]:
import pandas as pd
import numpy as np
data={
    "Name":["Alice","Bob","Charlie","David","Eve","Alice","Bob"],
    "Age":[25,30,22,np.nan,28,35,30],
    "Department":["HR","IT","Finance","HR","IT","HR","IT"],
    "Salary":[50000,60000,55000,np.nan,62000,70000,60000]
}
df=pd.DataFrame(data)
df.dropna(how='any')#any row that had only null value that will drop.

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  22.0    Finance  55000.0
4      Eve  28.0         IT  62000.0
5    Alice  35.0         HR  70000.0
6      Bob  30.0         IT  60000.0

In [ ]:
df.dropna(how='all')#all row that had only null value that will drop.

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  22.0    Finance  55000.0
3    David   NaN         HR      NaN
4      Eve  28.0         IT  62000.0
5    Alice  35.0         HR  70000.0

#Missing values
getting rid=>dropna

filling themup=>fillna

In [ ]:
df.fillna(0)

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  22.0    Finance  55000.0
3    David   0.0         HR      0.0
4      Eve  28.0         IT  62000.0
5    Alice  35.0         HR  70000.0

In [ ]:
df['Age'].fillna(df['Age'].mean())

0    25.0
1    30.0
2    22.0
3    28.0
4    28.0
5    35.0
Name: Age, dtype: float64

In [ ]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  22.0    Finance  55000.0
3    David  28.0         HR      NaN
4      Eve  28.0         IT  62000.0
5    Alice  35.0         HR  70000.0

In [ ]:
df['Salary'].fillna(df['Salary'].median())

0    50000.0
1    60000.0
2    55000.0
3    60000.0
4    62000.0
5    70000.0
Name: Salary, dtype: float64

#fillna()
forwardfill

backwardfill

In [ ]:
df['Salary'].fillna(method='ffill')

/tmp/ipython-input-2287196102.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Salary'].fillna(method='ffill')

0    50000.0
1    60000.0
2    55000.0
3    55000.0
4    62000.0
5    70000.0
Name: Salary, dtype: float64

In [ ]:
df['Salary'].fillna(method='bfill')

/tmp/ipython-input-2688032931.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Salary'].fillna(method='bfill')

0    50000.0
1    60000.0
2    55000.0
3    62000.0
4    62000.0
5    70000.0
Name: Salary, dtype: float64

In [ ]:
df['Name'].replace("Charlie","Ros")

0    Alice
1      Bob
2      Ros
3    David
4      Eve
5    Alice
Name: Name, dtype: object

#Duplicates

In [ ]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  22.0    Finance  55000.0
3    David   NaN         HR      NaN
4      Eve  28.0         IT  62000.0
5    Alice  35.0         HR  70000.0
6      Bob  30.0         IT  60000.0

In [ ]:
df_dup=df[df.duplicated()]
df_dup

  Name   Age Department   Salary
6  Bob  30.0         IT  60000.0

In [ ]:
df=df.drop_duplicates()
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  22.0    Finance  55000.0
3    David   NaN         HR      NaN
4      Eve  28.0         IT  62000.0
5    Alice  35.0         HR  70000.0

In [ ]:
#Invalid values
#Lambda=>python
df["Promotion Salary"]=df["Salary"]*10
df

/tmp/ipython-input-1148805034.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Promotion Salary"]=df["Salary"]*10

      Name   Age Department   Salary  Promotion Salary
0    Alice  25.0         HR  50000.0          500000.0
1      Bob  30.0         IT  60000.0          600000.0
2  Charlie  22.0    Finance  55000.0          550000.0
3    David   NaN         HR      NaN               NaN
4      Eve  28.0         IT  62000.0          620000.0
5    Alice  35.0         HR  70000.0          700000.0

In [ ]:
df['Promotion Salary']=df['Promotion Salary'].apply(lambda x:x/10 if x>60000 else x)
df

/tmp/ipython-input-1758132040.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Promotion Salary']=df['Promotion Salary'].apply(lambda x:x/10 if x>60000 else x)

      Name   Age Department   Salary  Promotion Salary
0    Alice  25.0         HR  50000.0           50000.0
1      Bob  30.0         IT  60000.0           60000.0
2  Charlie  22.0    Finance  55000.0           55000.0
3    David   NaN         HR      NaN               NaN
4      Eve  28.0         IT  62000.0           62000.0
5    Alice  35.0         HR  70000.0           70000.0

In [ ]:
import pandas as pd
data={
    "Name":["Alice_Markes","Bob_Ram","Charlie_Mital","David_Rao","Eve_Eil","Alice_Jordan","Bob_Harsh"]

}
df2=pd.DataFrame(data)
df2

            Name
0   Alice_Markes
1        Bob_Ram
2  Charlie_Mital
3      David_Rao
4        Eve_Eil
5   Alice_Jordan
6      Bob_Harsh

In [ ]:
df2[["First Name","Last Name"]]=df2["Name"].str.split("_",expand=True)
df2

            Name First Name Last Name
0   Alice_Markes      Alice    Markes
1        Bob_Ram        Bob       Ram
2  Charlie_Mital    Charlie     Mital
3      David_Rao      David       Rao
4        Eve_Eil        Eve       Eil
5   Alice_Jordan      Alice    Jordan
6      Bob_Harsh        Bob     Harsh

In [ ]:
#Apply and lambda
def multiply_age(x):
  return x*2
df["Age"]=df["Age"].apply(multiply_age)
df

/tmp/ipython-input-874433439.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"]=df["Age"].apply(multiply_age)

      Name   Age Department   Salary  Promotion Salary
0    Alice  50.0         HR  50000.0           50000.0
1      Bob  60.0         IT  60000.0           60000.0
2  Charlie  44.0    Finance  55000.0           55000.0
3    David   NaN         HR      NaN               NaN
4      Eve  56.0         IT  62000.0           62000.0
5    Alice  70.0         HR  70000.0           70000.0

In [ ]:
df["Age"]=df["Age"].apply(lambda x:x/2)
df

/tmp/ipython-input-124226412.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"]=df["Age"].apply(lambda x:x/2)

      Name   Age Department   Salary  Promotion Salary
0    Alice  25.0         HR  50000.0           50000.0
1      Bob  30.0         IT  60000.0           60000.0
2  Charlie  22.0    Finance  55000.0           55000.0
3    David   NaN         HR      NaN               NaN
4      Eve  28.0         IT  62000.0           62000.0
5    Alice  35.0         HR  70000.0           70000.0

#Joins and merges
joints=>left,right,outer&inner

In [ ]:
department_info={
    "Department":["HR","IT","Finance"],
    "Location":["New York","san frinciso","chicago"],
    "manager":["Alice","Steve","Nino"]
}
df3=pd.DataFrame(department_info)
df3

  Department      Location manager
0         HR      New York   Alice
1         IT  san frinciso   Steve
2    Finance       chicago    Nino

In [ ]:
pd.concat([df,df3])

      Name   Age Department   Salary  Promotion Salary      Location manager
0    Alice  25.0         HR  50000.0           50000.0           NaN     NaN
1      Bob  30.0         IT  60000.0           60000.0           NaN     NaN
2  Charlie  22.0    Finance  55000.0           55000.0           NaN     NaN
3    David   NaN         HR      NaN               NaN           NaN     NaN
4      Eve  28.0         IT  62000.0           62000.0           NaN     NaN
5    Alice  35.0         HR  70000.0           70000.0           NaN     NaN
0      NaN   NaN         HR      NaN               NaN      New York   Alice
1      NaN   NaN         IT      NaN               NaN  san frinciso   Steve
2      NaN   NaN    Finance      NaN               NaN       chicago    Nino

In [ ]:
pd.concat([df,df3],axis=1)

,Name,Age,Department,Salary,Promotion Salary,Department,Location,manager
0,Alice,25.0,HR,50000.0,50000.0,HR,New York,Alice
1,Bob,30.0,IT,60000.0,60000.0,IT,san frinciso,Steve
2,Charlie,22.0,Finance,55000.0,55000.0,Finance,chicago,Nino
3,David,NaN,HR,NaN,NaN,NaN,NaN,NaN
4,Eve,28.0,IT,62000.0,62000.0,NaN,NaN,NaN
5,Alice,35.0,HR,70000.0,70000.0,NaN,NaN,NaN

In [ ]:
pd.concat([df,df3],axis=0)

      Name   Age Department   Salary  Promotion Salary      Location manager
0    Alice  25.0         HR  50000.0           50000.0           NaN     NaN
1      Bob  30.0         IT  60000.0           60000.0           NaN     NaN
2  Charlie  22.0    Finance  55000.0           55000.0           NaN     NaN
3    David   NaN         HR      NaN               NaN           NaN     NaN
4      Eve  28.0         IT  62000.0           62000.0           NaN     NaN
5    Alice  35.0         HR  70000.0           70000.0           NaN     NaN
0      NaN   NaN         HR      NaN               NaN      New York   Alice
1      NaN   NaN         IT      NaN               NaN  san frinciso   Steve
2      NaN   NaN    Finance      NaN               NaN       chicago    Nino

In [ ]:
pd.merge(df,df3,on="Department")

      Name   Age Department   Salary  Promotion Salary      Location manager
0    Alice  25.0         HR  50000.0           50000.0      New York   Alice
1      Bob  30.0         IT  60000.0           60000.0  san frinciso   Steve
2  Charlie  22.0    Finance  55000.0           55000.0       chicago    Nino
3    David   NaN         HR      NaN               NaN      New York   Alice
4      Eve  28.0         IT  62000.0           62000.0  san frinciso   Steve
5    Alice  35.0         HR  70000.0           70000.0      New York   Alice

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving services_weekly.csv to services_weekly.csv

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv("services_weekly.csv")
df.head()

,week,month,service,available_beds,patients_request,patients_admitted,patients_refused,patient_satisfaction,staff_morale,event
0,1,1,emergency,32,76,32,44,67,70,none
1,1,1,surgery,45,130,45,85,83,78,flu
2,1,1,general_medicine,37,201,37,164,97,43,flu
3,1,1,ICU,22,31,22,9,84,91,flu
4,2,1,emergency,28,169,28,141,75,64,none

In [ ]:
print(df.shape)

(208, 10)

In [ ]:
print(df.columns)

Index(['week', 'month', 'service', 'available_beds', 'patients_request',
       'patients_admitted', 'patients_refused', 'patient_satisfaction',
       'staff_morale', 'event'],
      dtype='object')

In [ ]:
print(df.dtypes)

week                     int64
month                    int64
service                 object
available_beds           int64
patients_request         int64
patients_admitted        int64
patients_refused         int64
patient_satisfaction     int64
staff_morale             int64
event                   object
dtype: object

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   week                  208 non-null    int64
 1   month                 208 non-null    int64
 2   service               208 non-null    object
 3   available_beds        208 non-null    int64
 4   patients_request      208 non-null    int64
 5   patients_admitted     208 non-null    int64
 6   patients_refused      208 non-null    int64
 7   patient_satisfaction  208 non-null    int64
 8   staff_morale          208 non-null    int64
 9   event                 208 non-null    object
dtypes: int64(8), object(2)
memory usage: 16.4+ KB
None

In [ ]:
print(df.describe())

             week       month  available_beds  patients_request  \
count  208.000000  208.000000      208.000000        208.000000
mean    26.500000    6.923077       30.346154         64.870192
std     15.044539    3.634755       15.172929         58.738572
min      1.000000    1.000000        8.000000          5.000000
25%     13.750000    4.000000       18.000000         23.750000
50%     26.500000    7.000000       27.500000         49.000000
75%     39.250000   10.000000       40.000000         86.000000
max     52.000000   12.000000       74.000000        388.000000

       patients_admitted  patients_refused  patient_satisfaction  staff_morale
count         208.000000        208.000000            208.000000    208.000000
mean           28.129808         36.740385             80.000000     72.567308
std            14.676791         55.015763             11.125546     15.457759
min             5.000000          0.000000             60.000000     31.000000
25%            16.000000          0.000000             70.000000     60.000000
50%            26.000000         13.500000             81.000000     73.000000
75%            37.000000         52.500000             89.000000     86.000000
max            74.000000        363.000000             99.000000     99.000000

In [ ]:
print(df.isnull().sum())

week                    0
month                   0
service                 0
available_beds          0
patients_request        0
patients_admitted       0
patients_refused        0
patient_satisfaction    0
staff_morale            0
event                   0
dtype: int64

In [ ]:
print(df.duplicated().sum())

0

In [ ]:
print(df.corr(numeric_only=True))

                          week     month  available_beds  patients_request  \
week                  1.000000  0.995103        0.136608         -0.098087
month                 0.995103  1.000000        0.121017         -0.109450
available_beds        0.136608  0.121017        1.000000          0.262282
patients_request     -0.098087 -0.109450        0.262282          1.000000
patients_admitted     0.106035  0.094005        0.949928          0.370548
patients_refused     -0.133011 -0.141934        0.026614          0.968815
patient_satisfaction  0.004878 -0.004062        0.018831         -0.049699
staff_morale         -0.058352 -0.058633        0.093413          0.109494

                      patients_admitted  patients_refused  \
week                           0.106035         -0.133011
month                          0.094005         -0.141934
available_beds                 0.949928          0.026614
patients_request               0.370548          0.968815
patients_admitted              1.000000          0.128848
patients_refused               0.128848          1.000000
patient_satisfaction          -0.002337         -0.052439
staff_morale                   0.144855          0.078260

                      patient_satisfaction  staff_morale
week                              0.004878     -0.058352
month                            -0.004062     -0.058633
available_beds                    0.018831      0.093413
patients_request                 -0.049699      0.109494
patients_admitted                -0.002337      0.144855
patients_refused                 -0.052439      0.078260
patient_satisfaction              1.000000      0.008259
staff_morale                      0.008259      1.000000

In [ ]:
df.columns

Index(['week', 'month', 'service', 'available_beds', 'patients_request',
       'patients_admitted', 'patients_refused', 'patient_satisfaction',
       'staff_morale', 'event'],
      dtype='object')

In [ ]:
df["service"].value_counts()

service
emergency           52
surgery             52
general_medicine    52
ICU                 52
Name: count, dtype: int64

In [ ]:
df.dropna()

,week,month,service,available_beds,patients_request,patients_admitted,patients_refused,patient_satisfaction,staff_morale,event
0,1,1,emergency,32,76,32,44,67,70,none
1,1,1,surgery,45,130,45,85,83,78,flu
2,1,1,general_medicine,37,201,37,164,97,43,flu
3,1,1,ICU,22,31,22,9,84,91,flu
4,2,1,emergency,28,169,28,141,75,64,none
...,...,...,...,...,...,...,...,...,...,...
203,51,12,ICU,18,15,15,0,87,80,none
204,52,12,emergency,26,130,26,104,88,63,none
205,52,12,surgery,53,39,39,0,82,50,none
206,52,12,general_medicine,65,225,65,160,82,40,flu
207,52,12,ICU,22,24,22,2,80,96,none

In [ ]:
df.dropna(how="any")

,week,month,service,available_beds,patients_request,patients_admitted,patients_refused,patient_satisfaction,staff_morale,event
0,1,1,emergency,32,76,32,44,67,70,none
1,1,1,surgery,45,130,45,85,83,78,flu
2,1,1,general_medicine,37,201,37,164,97,43,flu
3,1,1,ICU,22,31,22,9,84,91,flu
4,2,1,emergency,28,169,28,141,75,64,none
...,...,...,...,...,...,...,...,...,...,...
203,51,12,ICU,18,15,15,0,87,80,none
204,52,12,emergency,26,130,26,104,88,63,none
205,52,12,surgery,53,39,39,0,82,50,none
206,52,12,general_medicine,65,225,65,160,82,40,flu
207,52,12,ICU,22,24,22,2,80,96,none

In [ ]:
df.dropna(how="all")

,week,month,service,available_beds,patients_request,patients_admitted,patients_refused,patient_satisfaction,staff_morale,event
0,1,1,emergency,32,76,32,44,67,70,none
1,1,1,surgery,45,130,45,85,83,78,flu
2,1,1,general_medicine,37,201,37,164,97,43,flu
3,1,1,ICU,22,31,22,9,84,91,flu
4,2,1,emergency,28,169,28,141,75,64,none
...,...,...,...,...,...,...,...,...,...,...
203,51,12,ICU,18,15,15,0,87,80,none
204,52,12,emergency,26,130,26,104,88,63,none
205,52,12,surgery,53,39,39,0,82,50,none
206,52,12,general_medicine,65,225,65,160,82,40,flu
207,52,12,ICU,22,24,22,2,80,96,none

In [ ]:
df["event"].value_counts()

event
none        164
flu          19
donation     14
strike       11
Name: count, dtype: int64

In [ ]:
#Duplicates
df_dup=df[df.duplicated()]
df_dup

Empty DataFrame
Columns: [week, month, service, available_beds, patients_request, patients_admitted, patients_refused, patient_satisfaction, staff_morale, event]
Index: []

In [ ]:
df1=df.drop_duplicates
df1

<bound method DataFrame.drop_duplicates of      week  month           service  available_beds  patients_request  \
0       1      1         emergency              32                76
1       1      1           surgery              45               130
2       1      1  general_medicine              37               201
3       1      1               ICU              22                31
4       2      1         emergency              28               169
..    ...    ...               ...             ...               ...
203    51     12               ICU              18                15
204    52     12         emergency              26               130
205    52     12           surgery              53                39
206    52     12  general_medicine              65               225
207    52     12               ICU              22                24

     patients_admitted  patients_refused  patient_satisfaction  staff_morale  \
0                   32                44                    67            70
1                   45                85                    83            78
2                   37               164                    97            43
3                   22                 9                    84            91
4                   28               141                    75            64
..                 ...               ...                   ...           ...
203                 15                 0                    87            80
204                 26               104                    88            63
205                 39                 0                    82            50
206                 65               160                    82            40
207                 22                 2                    80            96

    event
0    none
1     flu
2     flu
3     flu
4    none
..    ...
203  none
204  none
205  none
206   flu
207  none

[208 rows x 10 columns]>